sudo: required

compiler: gcc

env: COMPILER=g++-4.8

before_install:
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-add-repository -y ppa:beineri/opt-qt542
    - sudo apt-get -qq update
    - sudo apt-get -qq install g++-4.8 libc6-i386 qt54tools qt54svg qt54webkit qt54serialport
    - export CXX="g++-4.8"
    - PATH="/opt/qt54/bin:$PATH"
    - qt54-env.sh
    - mkdir -p build/.lib/
    - cd src

install:
    # it seems as currently the redirect to the latest version is buggy when using wget (always windows version delivered
    #- wget 'https://sourceforge.net/projects/astyle/files/latest/download'
    # workaround hard code to newest version
    - wget "https://sourceforge.net/projects/astyle/files/astyle/astyle%202.06/astyle_2.06_linux.tar.gz/download"
    - tar -zxvf download
    - (cd astyle/build/gcc && make release && sudo make install)
    - rm astyle -rf
    - git clone https://github.com/google/googletest.git
    - cd googletest
    - sudo cp -r googletest/include/gtest /usr/local/include
    - sudo cp -r googlemock/include/gmock /usr/local/include
    - g++ -isystem googletest/include/ -Igoogletest -isystem googlemock/include/ -Igooglemock -pthread -c googlemock/src/gmock-all.cc
    - g++ -isystem googletest/include/ -Igoogletest -isystem googlemock/include/ -Igooglemock -pthread -c googletest/src/gtest-all.cc
    - ar -rv libgmock.a gtest-all.o gmock-all.o
    - cp libgmock.a ../../build/.lib/
    - cd ..

script:
    - sudo mv /usr/bin/g++ /usr/bin/g++_depr
    - sudo ln -s $(which $CXX) /usr/bin/g++
    - $CXX --version
    - g++ --version
    - qmake
    - ls ../build/.lib/
    - make
    - cd ..
    - "! (astyle *.h *.cpp -r --dry-run --options=astylerc --exclude=googletest | grep formatted)"
    # maybe not needed
    - sudo mv /usr/bin/g++_depr /usr/bin/g++

language: cpp
